package com.tcl.aota.persistent.model;

import java.util.Date;

import com.tcl.aota.common.utils.DateUtil;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.admin_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.admin_pass
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private String adminPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.version
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.create_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_admin.update_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.id
     *
     * @return the value of aota_admin.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.id
     *
     * @param id the value for aota_admin.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.admin_name
     *
     * @return the value of aota_admin.admin_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.admin_name
     *
     * @param adminName the value for aota_admin.admin_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.admin_pass
     *
     * @return the value of aota_admin.admin_pass
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getAdminPass() {
        return adminPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.admin_pass
     *
     * @param adminPass the value for aota_admin.admin_pass
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setAdminPass(String adminPass) {
        this.adminPass = adminPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.version
     *
     * @return the value of aota_admin.version
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.version
     *
     * @param version the value for aota_admin.version
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.create_Time
     *
     * @return the value of aota_admin.create_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.create_Time
     *
     * @param createTime the value for aota_admin.create_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_admin.update_Time
     *
     * @return the value of aota_admin.update_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getUpdateTime() {
        return DateUtil.fomartDateToStr("yyyy-MM-dd HH:mm:ss", updateTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_admin.update_Time
     *
     * @param updateTime the value for aota_admin.update_Time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}