package com.tcl.aota.persistent.model;

import java.io.Serializable;
import java.util.Date;

import com.tcl.aota.common.utils.DateUtil;

public class App implements Serializable {
    private static final long serialVersionUID = 4421765506221226766L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.id
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_name
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appName;

    /**
     * app包名
     */
    private String apkPackName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_size
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_start_grade
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appStartGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_developer
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appDeveloper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_detail
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_permission
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_icon
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_imgs
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.source_channel
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String sourceChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.version_name
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.version_code
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_url
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.app_sequence
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Integer appSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.trash
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Byte trash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.package_id
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Long packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.create_Time
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_app.update_Time
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.id
     *
     * @return the value of aota_app.id
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.id
     *
     * @param id the value for aota_app.id
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_name
     *
     * @return the value of aota_app.app_name
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_name
     *
     * @param appName the value for aota_app.app_name
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_size
     *
     * @return the value of aota_app.app_size
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppSize() {
        return appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_size
     *
     * @param appSize the value for aota_app.app_size
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppSize(String appSize) {
        this.appSize = appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_start_grade
     *
     * @return the value of aota_app.app_start_grade
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppStartGrade() {
        return appStartGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_start_grade
     *
     * @param appStartGrade the value for aota_app.app_start_grade
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppStartGrade(String appStartGrade) {
        this.appStartGrade = appStartGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_developer
     *
     * @return the value of aota_app.app_developer
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppDeveloper() {
        return appDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_developer
     *
     * @param appDeveloper the value for aota_app.app_developer
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppDeveloper(String appDeveloper) {
        this.appDeveloper = appDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_detail
     *
     * @return the value of aota_app.app_detail
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppDetail() {
        return appDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_detail
     *
     * @param appDetail the value for aota_app.app_detail
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppDetail(String appDetail) {
        this.appDetail = appDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_permission
     *
     * @return the value of aota_app.app_permission
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppPermission() {
        return appPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_permission
     *
     * @param appPermission the value for aota_app.app_permission
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppPermission(String appPermission) {
        this.appPermission = appPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_icon
     *
     * @return the value of aota_app.app_icon
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppIcon() {
        return appIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_icon
     *
     * @param appIcon the value for aota_app.app_icon
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppIcon(String appIcon) {
        this.appIcon = appIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_imgs
     *
     * @return the value of aota_app.app_imgs
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppImgs() {
        return appImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_imgs
     *
     * @param appImgs the value for aota_app.app_imgs
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppImgs(String appImgs) {
        this.appImgs = appImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.source_channel
     *
     * @return the value of aota_app.source_channel
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getSourceChannel() {
        if (sourceChannel != null) {
            if ("1".equals(sourceChannel)) {
                sourceChannel = "The official recommendation";
            } else if ("2".equals(sourceChannel)) {
                sourceChannel = "Third party access";
            } else if ("3".equals(sourceChannel)) {
                sourceChannel = "Free developers";
            }
        }
        return sourceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.source_channel
     *
     * @param sourceChannel the value for aota_app.source_channel
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setSourceChannel(String sourceChannel) {
        this.sourceChannel = sourceChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.version_name
     *
     * @return the value of aota_app.version_name
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.version_name
     *
     * @param versionName the value for aota_app.version_name
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.version_code
     *
     * @return the value of aota_app.version_code
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.version_code
     *
     * @param versionCode the value for aota_app.version_code
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_url
     *
     * @return the value of aota_app.app_url
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_url
     *
     * @param appUrl the value for aota_app.app_url
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.app_sequence
     *
     * @return the value of aota_app.app_sequence
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public Integer getAppSequence() {
        return appSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.app_sequence
     *
     * @param appSequence the value for aota_app.app_sequence
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setAppSequence(Integer appSequence) {
        this.appSequence = appSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.trash
     *
     * @return the value of aota_app.trash
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public Byte getTrash() {
        return trash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.trash
     *
     * @param trash the value for aota_app.trash
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setTrash(Byte trash) {
        this.trash = trash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.package_id
     *
     * @return the value of aota_app.package_id
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public Long getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.package_id
     *
     * @param packageId the value for aota_app.package_id
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setPackageId(Long packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.create_Time
     *
     * @return the value of aota_app.create_Time
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getCreateTime() {
        return DateUtil.fomartDateToStr("yyyy-MM-dd HH:mm:ss", createTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.create_Time
     *
     * @param createTime the value for aota_app.create_Time
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_app.update_Time
     *
     * @return the value of aota_app.update_Time
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public String getUpdateTime() {
        return DateUtil.fomartDateToStr("yyyy-MM-dd HH:mm:ss", updateTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_app.update_Time
     *
     * @param updateTime the value for aota_app.update_Time
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    public String getApkPackName() {
        return apkPackName;
    }

    public void setApkPackName(String apkPackName) {
        this.apkPackName = apkPackName;
    }
}