package com.tcl.aota.persistent.model;

import java.util.Date;

import com.tcl.aota.common.utils.DateUtil;

public class Package {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.package_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.app_quantity
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Integer appQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.package_size
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Float packageSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.create_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.release_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_package.package_sequence
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Integer packageSequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.id
     *
     * @return the value of aota_package.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.id
     *
     * @param id the value for aota_package.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.package_name
     *
     * @return the value of aota_package.package_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.package_name
     *
     * @param packageName the value for aota_package.package_name
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.app_quantity
     *
     * @return the value of aota_package.app_quantity
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Integer getAppQuantity() {
        return appQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.app_quantity
     *
     * @param appQuantity the value for aota_package.app_quantity
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setAppQuantity(Integer appQuantity) {
        this.appQuantity = appQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.package_size
     *
     * @return the value of aota_package.package_size
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Float getPackageSize() {
        return packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.package_size
     *
     * @param packageSize the value for aota_package.package_size
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setPackageSize(Float packageSize) {
        this.packageSize = packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.create_time
     *
     * @return the value of aota_package.create_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public String getCreateTime() {
        return DateUtil.fomartDateToStr("yyyy-MM-dd HH:mm:ss", createTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.create_time
     *
     * @param createTime the value for aota_package.create_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.release_time
     *
     * @return the value of aota_package.release_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.release_time
     *
     * @param releaseTime the value for aota_package.release_time
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aota_package.package_sequence
     *
     * @return the value of aota_package.package_sequence
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public Integer getPackageSequence() {
        return packageSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aota_package.package_sequence
     *
     * @param packageSequence the value for aota_package.package_sequence
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    public void setPackageSequence(Integer packageSequence) {
        this.packageSequence = packageSequence;
    }
}