package com.tcl.aota.persistent.model;

public class Strategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_strategy.id
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Long id;

    /**
     * 检测周期
     */
    private Integer upgradePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_strategy.auto_downflag
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Byte autoDownwifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_strategy.del_apkflag
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Byte delUpgradeapk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aota_strategy.clear_cache_flag
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    private Byte clearCache;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUpgradePeriod() {
        return upgradePeriod;
    }

    public void setUpgradePeriod(Integer upgradePeriod) {
        this.upgradePeriod = upgradePeriod;
    }

    public Byte getAutoDownwifi() {
        return autoDownwifi;
    }

    public void setAutoDownwifi(Byte autoDownwifi) {
        this.autoDownwifi = autoDownwifi;
    }

    public Byte getDelUpgradeapk() {
        return delUpgradeapk;
    }

    public void setDelUpgradeapk(Byte delUpgradeapk) {
        this.delUpgradeapk = delUpgradeapk;
    }

    public Byte getClearCache() {
        return clearCache;
    }

    public void setClearCache(Byte clearCache) {
        this.clearCache = clearCache;
    }
}