package com.tcl.aota.persistent.dao.db;

import java.util.List;
import java.util.Map;


import com.tcl.aota.persistent.model.App;

public interface AppDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_app
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_app
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_app
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    App selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_app
     *
     * @mbggenerated Tue Oct 28 12:08:13 CST 2014
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * get app list by packageId
     *
     * @return
     */
    List<App> selectAppListByPackageId(Long packageId);

    /**
     * get app list by Ids
     *
     * @return
     */
    List<App> selectAppListByIds(List<Long> ids);


    /**
     * set app's package_id = 0
     *
     * @return
     */
    int recoveryApp(List<Long> packageIds);

    /**
     * batch delete
     *
     * @return
     */
    int deleteByIds(List<Long> ids);

    /**
     * batch trash
     *
     * @return
     */
    int trashOpt(Map<String, Object> params);


    /**
     * update app by sequence
     *
     * @param parame
     * @return
     */
    int updateAppBySeq(Map<String,Object> parame);

    /**
     * get app count by condition map
     *
     * @param param
     * @return
     */
    int selectAppCountByConds(Map<String, Object> param);

    /**
     * get app list by condition map
     *
     * @param param
     * @return
     */
    List<App> selectAppListByConds(Map<String, Object> param);


    /**
     * batch put to package
     *
     * @param param
     * @return
     */
    int putAppToPackage(Map<String, Object> param);
}