package com.tcl.aota.persistent.dao.db;

import java.util.List;
import java.util.Map;


import com.tcl.aota.persistent.model.Package;

public interface PackageDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_package
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int deleteByPrimaryKey(Long id);
    
    int deleteByPrimaryKeys(List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_package
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int insert(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_package
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    Package selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_package
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int updateByPrimaryKeySelective(Package record);


    /**
     * 获取最新发布的一个包
     * @return
     */
    Package selectLatestPackage();
    
    /**
     * 按条件查询包信息
     * return List<Package>
     */
    List<Package> selectPackages(Map<String, Object> condition);
    
    /**
     * 发布包
     * return int
     */
    int releasePackages(Map<String,Object> param);
}