package com.tcl.aota.persistent.dao.db;

import com.tcl.aota.persistent.model.Strategy;

public interface StrategyDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_strategy
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_strategy
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_strategy
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    Strategy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aota_strategy
     *
     * @mbggenerated Tue Oct 28 09:29:17 CST 2014
     */
    int updateByPrimaryKeySelective(Strategy record);


    /**
     * get config of strategy
     * @return
     */
    Strategy selectStrategyConfig();
}